mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from register import views as rv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', rv.register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', rv.activate, name='activate'),
    path('accounts/register/please_check_email', rv.please_check_email, name='please_check_email'),
    path('accounts/register/invalid_link', rv.invalid_link, name='invalid_link'),
    path('accounts/register/thank_you', rv.thank_you, name='thank_you'),
    path('', include('viewer.urls')),
]

mysite/viewer/urls.py
from django.urls import path
from . import views

app_name = 'viewer'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('help', views.get_help, name='help'),
    path('privacy', views.privacy, name='privacy'),

    ## Tutorials
    path('tutorials', views.enable_tutorials, name='enable_tutorials'),
    
    ## Models
    # Lipid
    path('lipid/<slug:lipid_name>', views.lipid_detail, name='lipid_detail'),
    path('lipid/<int:owner>/custom/new', views.user_lipid_new, name='user_lipid_new'),
    path('lipid/<int:owner>/custom/<slug:lipid_name>/edit', views.user_lipid_edit, name='user_lipid_edit'),
    path('lipid/<int:owner>/custom/<slug:lipid_name>', views.user_lipid_detail, name='user_lipid_detail'),
    # Molecule
    path('molecule/<slug:molecule_name>', views.molecule_detail, name='molecule_detail'),

    ## Pojects
    # New project
    path('project/new', views.project_new, name='project_new'),
    # List projects
    path('project/list', views.project_list, name='project_list'),
    # Project details
    path('project/<int:project_id>', views.project_detail, name='project_detail'),
    # Turn on advanced options for this project
    path('project/<int:project_id>/advanced/', views.project_advanced_options, name='project_advanced_options'),
    # Edit a project
    path('project/<int:project_id>/edit/', views.project_edit, name='project_edit'),
    # Warning & delete project
    path('project/<int:project_id>/delete_warning/', views.project_delete_warning, name='project_delete_warning'),

    ## Project Lipids
    # Add project lipid
    path('project/<int:project_id>/lipid/add/', views.project_lipid_new, name='project_lipid_new'),
    # Add project custom lipid volume
    path('project/<int:project_id>/lipid/<int:lipid_id>/add-volume/', views.project_user_lipid_volume_new, name='project_user_lipid_volume_new'),
    # Edit project custom lipid volume
    path('project/<int:project_id>/lipid/<int:volume_id>/edit-volume/', views.project_user_lipid_volume_edit, name='project_user_lipid_volume_edit'),
    # # Edit a project lipid
    # path('project/<int:project_id>/lipid/<int:lipid_id>/edit/', views.project_lipid_edit, name='project_lipid_edit'),
    # Warning & delete lipid
    path('project/<int:project_id>/lipid/<int:lipid_id>/delete_warning/', views.project_lipid_delete_warning, name='project_lipid_delete_warning'),

    ## Samples
    # New project
    path('project/<int:project_id>/sample/new', views.sample_new, name='sample_new'),
    # Sample details
    path('project/<int:project_id>/sample/<int:sample_id>', views.sample_detail, name='sample_detail'),
    # Edit a sample
    path('project/<int:project_id>/sample/<int:sample_id>/edit/', views.sample_edit, name='sample_edit'),
    # Warning & delete sample
    path('project/<int:project_id>/sample/<int:sample_id>/delete_warning/', views.sample_delete_warning, name='sample_delete_warning'),

    ## Sample Lipids
    # Add sample lipid
    path('project/<int:project_id>/sample/<int:sample_id>/lipid/add/', views.sample_lipid_new, name='sample_lipid_new'),
    # Edit a sample lipid
    path('project/<int:project_id>/sample/<int:sample_id>/lipid/<int:lipid_id>/edit/', views.sample_lipid_edit, name='sample_lipid_edit'),
    # Edit custom augments
    path('project/<int:project_id>/sample/<int:sample_id>/lipid/<int:lipid_id>/custom/', views.sample_custom_lipid_edit, name='sample_custom_lipid_edit'),
    # Warning & delete lipid
    path('project/<int:project_id>/sample/<int:sample_id>/lipid/<int:lipid_id>/delete_warning/', views.sample_lipid_delete_warning, name='sample_lipid_delete_warning'),

    ## Sym Parameters
    # Add project parameters
    path('project/<int:project_id>/sample/<int:sample_id>/symparameters/new/', views.symmetrical_parameters_new, name='symmetrical_parameters_new'),
    # Edit a projects parameters
    path('project/<int:project_id>/sample/<int:sample_id>/symparameters/<int:parameter_id>/edit/', views.symmetrical_parameters_edit, name='symmetrical_parameters_edit'),
    # Warning & delete parameters
    path('project/<int:project_id>/sample/<int:sample_id>/symparameters/<int:parameter_id>/delete_warning/', views.symmetrical_parameter_delete_warning, name='symmetrical_parameter_delete_warning'),

    ## Asym Parameters
    # Add project parameters
    path('project/<int:project_id>/sample/<int:sample_id>/asymparameters/new/', views.asymmetrical_parameters_new, name='asymmetrical_parameters_new'),
    # Edit a projects parameters
    path('project/<int:project_id>/sample/<int:sample_id>/asymparameters/<int:parameter_id>/edit/', views.asymmetrical_parameters_edit, name='asymmetrical_parameters_edit'),
    # Warning & delete parameters
    path('project/<int:project_id>/sample/<int:sample_id>/asymparameters/<int:parameter_id>/delete_warning/', views.asymmetrical_parameter_delete_warning, name='asymmetrical_parameter_delete_warning'),

    ## Data
    # Upload data
    path('project/<int:project_id>/sample/<int:sample_id>/data/upload/', views.data_upload, name='data_upload'),
    # Edit data files
    path('project/<int:project_id>/sample/<int:sample_id>/data/<int:data_id>/edit/', views.data_edit, name='data_edit'),
    # Warning & delete data
    path('project/<int:project_id>/sample/<int:sample_id>/data/<int:data_id>/delete_warning/', views.data_delete_warning, name='data_delete_warning'),

    ## Fitting
    # Sym fit page
    path('project/<int:project_id>/sample/<int:sample_id>/fit/<int:parameter_id>/', views.fit_main, name='fit_main'),
]

mysite/templates/base.html
{% load staticfiles%}

<!DOCTYPE html>
<html>
<head>
    <title>Vesicle Viewer | {% block title %}{% endblock %}</title>

    {% block head_meta %}
        {% block head_meta_charset %}
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        {% endblock head_meta_charset %}
        {% block head_meta_contentlanguage %}
            <meta http-equiv="Content-Language" value="en-US" />
        {% endblock head_meta_contentlanguage %}
        {% block head_meta_viewport %}
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% endblock head_meta_viewport %}
    {% endblock head_meta %}

    {% block head_css %}
        {% block head_css_site %}
            <link rel="stylesheet" type="text/css" href="{% static 'viewer/style.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'viewer/tooltips.css' %}">
            <link href="https://fonts.googleapis.com/css?family=Manjari:100,400,700&display=swap" rel="stylesheet">
        {% endblock head_css_site %}
        {% block head_css_section %}{% endblock head_css_section %}
        {% block head_css_page %}{% endblock head_css_page %}
    {% endblock head_css %}
</head>

<body>

    {# Header #}
    <header>
        <div class='header-text'>
            <a href="{% url 'viewer:index' %}">
                <img src="{% static "viewer/images/viewericon.png" %}" width="30px">
                <h3>Vesicle Viewer</h3>
            </a>
        </div>

        {# Navigation #}
        <nav>
            <ul>
                <li><a href="{% url 'viewer:about' %}">About</a></li>
                <li><a href="{% url 'viewer:help' %}">Help</a></li>
                <li><a href="{% url 'viewer:privacy' %}">Privacy</a></li>
                {% if user.is_authenticated %}
                    <li class="button-style"><a href="{% url 'viewer:project_list' %}">Projects</a></li>
                    <li class="sign-in"><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li class="sign-in"><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    {# Main content #}
    <main>
        {% block content %}
        {% endblock %}
    </main>

    {# Footer #}
    <footer>
        <p>Developed and supported by the LABR research team at the University of Windsor in collaboration with the
            University of Tennessee.</p>
        <p>>> Last updated 04/27/2021</p>
        <p>>> <em>version BETA 2.0</em></p>
        <br />
        <p>>> DOI: <a href="https://doi.org/10.26434/chemrxiv.14454645.v1">https://doi.org/10.26434/chemrxiv.14454645.v1</a> </p>
        <p>>> <a href="{% url 'viewer:about' %}">Cite this tool in your work</a></p>
        <p>>> <a href="https://github.com/AislynLaurent/vesicle-viewer/issues">Report an issue</a></p>
        {% if user.is_authenticated %}
            <p>>> <a href="{% url 'viewer:enable_tutorials' %}">Permanently enable or disable tutorials</a></p>
        {% endif %}
    </footer>

</body>
</html>