mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from register import views as rv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', rv.register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', rv.activate, name='activate'),
    path('accounts/register/please_check_email', rv.please_check_email, name='please_check_email'),
    path('accounts/register/invalid_link', rv.invalid_link, name='invalid_link'),
    path('accounts/register/thank_you', rv.thank_you, name='thank_you'),
    path('', include('viewer.urls')),
]

mysite/viewer/urls.py
from django.urls import path
from . import views

app_name = 'viewer'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('help', views.get_help, name='help'),
    path('privacy', views.privacy, name='privacy'),

    ## Tutorials
    path('tutorials', views.enable_tutorials, name='enable_tutorials'),
    
    ## Models
    # Lipid
    path('lipid/<slug:lipid_name>', views.lipid_detail, name='lipid_detail'),
    path('lipid/<int:owner>/custom/new', views.user_lipid_new, name='user_lipid_new'),
    path('lipid/<int:owner>/custom/<slug:lipid_name>/edit', views.user_lipid_edit, name='user_lipid_edit'),
    path('lipid/<int:owner>/custom/<slug:lipid_name>', views.user_lipid_detail, name='user_lipid_detail'),
    # Molecule
    path('molecule/<slug:molecule_name>', views.molecule_detail, name='molecule_detail'),

    ## Pojects
    # New project
    path('project/new', views.project_new, name='project_new'),
    # List projects
    path('project/list', views.project_list, name='project_list'),
    # Project details
    path('project/<int:project_id>', views.project_detail, name='project_detail'),
    # Turn on advanced options for this project
    path('project/<int:project_id>/advanced/', views.project_advanced_options, name='project_advanced_options'),
    # Edit a project
    path('project/<int:project_id>/edit/', views.project_edit, name='project_edit'),
    # Warning & delete project
    path('project/<int:project_id>/delete_warning/', views.project_delete_warning, name='project_delete_warning'),

    ## Project Lipids
    # Add project lipid
    path('project/<int:project_id>/lipid/add/', views.project_lipid_new, name='project_lipid_new'),
    # Add project custom lipid volume
    path('project/<int:project_id>/lipid/<int:lipid_id>/add-volume/', views.project_user_lipid_volume_new, name='project_user_lipid_volume_new'),
    # Edit project custom lipid volume
    path('project/<int:project_id>/lipid/<int:volume_id>/edit-volume/', views.project_user_lipid_volume_edit, name='project_user_lipid_volume_edit'),
    # # Edit a project lipid
    # path('project/<int:project_id>/lipid/<int:lipid_id>/edit/', views.project_lipid_edit, name='project_lipid_edit'),
    # Warning & delete lipid
    path('project/<int:project_id>/lipid/<int:lipid_id>/delete_warning/', views.project_lipid_delete_warning, name='project_lipid_delete_warning'),

    ## Samples
    # New project
    path('project/<int:project_id>/sample/new', views.sample_new, name='sample_new'),
    # Sample details
    path('project/<int:project_id>/sample/<int:sample_id>', views.sample_detail, name='sample_detail'),
    # Edit a sample
    path('project/<int:project_id>/sample/<int:sample_id>/edit/', views.sample_edit, name='sample_edit'),
    # Warning & delete sample
    path('project/<int:project_id>/sample/<int:sample_id>/delete_warning/', views.sample_delete_warning, name='sample_delete_warning'),

    ## Sample Lipids
    # Add sample lipid
    path('project/<int:project_id>/sample/<int:sample_id>/lipid/add/', views.sample_lipid_new, name='sample_lipid_new'),
    # Edit a sample lipid
    path('project/<int:project_id>/sample/<int:sample_id>/lipid/<int:lipid_id>/edit/', views.sample_lipid_edit, name='sample_lipid_edit'),
    # Edit custom augments
    path('project/<int:project_id>/sample/<int:sample_id>/lipid/<int:lipid_id>/custom/', views.sample_custom_lipid_edit, name='sample_custom_lipid_edit'),
    # Warning & delete lipid
    path('project/<int:project_id>/sample/<int:sample_id>/lipid/<int:lipid_id>/delete_warning/', views.sample_lipid_delete_warning, name='sample_lipid_delete_warning'),

    ## Sym Parameters
    # Add project parameters
    path('project/<int:project_id>/sample/<int:sample_id>/symparameters/new/', views.symmetrical_parameters_new, name='symmetrical_parameters_new'),
    # Edit a projects parameters
    path('project/<int:project_id>/sample/<int:sample_id>/symparameters/<int:parameter_id>/edit/', views.symmetrical_parameters_edit, name='symmetrical_parameters_edit'),
    # Warning & delete parameters
    path('project/<int:project_id>/sample/<int:sample_id>/symparameters/<int:parameter_id>/delete_warning/', views.symmetrical_parameter_delete_warning, name='symmetrical_parameter_delete_warning'),

    ## Asym Parameters
    # Add project parameters
    path('project/<int:project_id>/sample/<int:sample_id>/asymparameters/new/', views.asymmetrical_parameters_new, name='asymmetrical_parameters_new'),
    # Edit a projects parameters
    path('project/<int:project_id>/sample/<int:sample_id>/asymparameters/<int:parameter_id>/edit/', views.asymmetrical_parameters_edit, name='asymmetrical_parameters_edit'),
    # Warning & delete parameters
    path('project/<int:project_id>/sample/<int:sample_id>/asymparameters/<int:parameter_id>/delete_warning/', views.asymmetrical_parameter_delete_warning, name='asymmetrical_parameter_delete_warning'),

    ## Data
    # Upload data
    path('project/<int:project_id>/sample/<int:sample_id>/data/upload/', views.data_upload, name='data_upload'),
    # Edit data files
    path('project/<int:project_id>/sample/<int:sample_id>/data/<int:data_id>/edit/', views.data_edit, name='data_edit'),
    # Warning & delete data
    path('project/<int:project_id>/sample/<int:sample_id>/data/<int:data_id>/delete_warning/', views.data_delete_warning, name='data_delete_warning'),

    ## Fitting
    # Sym fit page
    path('project/<int:project_id>/sample/<int:sample_id>/fit/<int:parameter_id>/', views.fit_main, name='fit_main'),
]

mysite/viewer/views.py
## IMPORTS
# From django
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect

# Other libraries
import re

# Models
from .models import *

# Forms
from .forms import *

# Other imports
from .symfit import *
from .asymfit import *
from .probabilities import *

# note: test if you need the above imports, as most of these imports are needed in fit.py as well
from viewer.fit import generate_fit_main

## STATIC PAGES
# Home
def index(request):
    ## Import
    if request.user.is_anonymous:
        xuser_tutorial = False
    else:
        xuser = ExtendedUser.objects.get(user=request.user)
        xuser_tutorial = xuser.display_tutorial
    
    tutorial = True

    # Forms
    # Dismiss the tutorial
    if "dismiss_this" in request.POST:
        tutorial = False

    # Dismiss all tutorials
    if "dismiss_all" in request.POST:
        xuser.display_tutorial = False
        xuser.save()

    return render(
        request,
        'viewer/index.html', {
            'tutorial':tutorial,
            'xuser_tutorial':xuser_tutorial,
        }
    )

# About
def about(request):
    context = {}
    return render(request, 'viewer/about.html', context)
# Help
def get_help(request):
    context = {}
    return render(request, 'viewer/help.html', context)
# Privacy Policy
def privacy(request):
    context = {}
    return render(request, 'viewer/privacy.html', context)

# Tutorial Form
def enable_tutorials(request):
    ## Import
    x_user = get_object_or_404(ExtendedUser, user=request.user)

    if request.method == 'POST':
        form = Tutorial_Form(request.POST, instance=x_user)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()
            return redirect('viewer:index')
    else:
        form = Tutorial_Form(instance=x_user)

    return render(request, 'viewer/form.html', {'form': form})

## MODEL PAGES
# Lipid
def lipid_detail(request, lipid_name):
    lipid = get_object_or_404(Lipid, slug=lipid_name)
    return render(request, 'viewer/lipid_detail.html', {'lipid':lipid})

# Custom lipid
def user_lipid_detail(request, owner, lipid_name):
    lipid = get_object_or_404(User_Lipid, slug=lipid_name, owner=owner)
    return render(request, 'viewer/lipid_detail.html', {'lipid':lipid})

# New custom lipid
def user_lipid_new(request, owner):
    if request.method == 'POST':
        form = User_Lipid_Form(request.POST)
        if form.is_valid():
            lipids = form.save(commit=False)
            lipids.owner = request.user
            lipids.save()
            return redirect('viewer:project_list')
    else:
        form = User_Lipid_Form()

    return render(request, 'viewer/form.html', {'form': form})

# Edit user lipid
def user_lipid_edit(request, owner, lipid_name):
    lipid = get_object_or_404(User_Lipid, slug=lipid_name, owner=owner)

    if request.method == 'POST':
        form = User_Lipid_Form(request.POST, instance=lipid)
        if form.is_valid():
            lipids = form.save(commit=False)
            lipids.owner = request.user
            lipids.save()
            return redirect('viewer:project_list')
    else:
        form = User_Lipid_Form(instance=lipid)

    return render(request, 'viewer/form.html', {'form': form})

# Molecule
def molecule_detail(request, molecule_name):
    molecule = get_object_or_404(Molecule, slug=molecule_name)
    return render(request, 'viewer/lipid_detail.html', {'molecule':molecule})

## DYNAMIC PAGES
## Project stuff
# Start a new project
def project_new(request):
    if request.method == 'POST':
        form = Project_Form(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user
            project.save()
            return redirect('viewer:project_detail', project_id=project.id)
    else:
        form = Project_Form()
    return render(request, 'viewer/form.html', {'form': form})

# List existing projects
def project_list(request):
    ## Tutorials
    if request.user.is_anonymous:
        xuser_tutorial = False
    else:
        xuser = ExtendedUser.objects.get(user=request.user)
        xuser_tutorial = xuser.display_tutorial
    tutorial = True
    # Dismiss the tutorial
    if "dismiss_this" in request.POST:
        tutorial = False

    # Dismiss all tutorials
    if "dismiss_all" in request.POST:
        xuser.display_tutorial = False
        xuser.save()
    
    ## List
    symmetrical_projects = Project.objects.filter(owner=request.user, model_type='SM').order_by('project_title')
    asymmetrical_projects = Project.objects.filter(owner=request.user, model_type='AS').order_by('project_title')
    user_lipids = User_Lipid.objects.filter(owner=request.user).order_by('user_lipid_name')

    return render(
        request,
        'viewer/project_list.html', {
            'tutorial':tutorial,
            'xuser_tutorial':xuser_tutorial,
            'symmetrical_projects':symmetrical_projects,
            'asymmetrical_projects':asymmetrical_projects,
            'user_lipids':user_lipids,
        }
    )

# Specific project details
def project_detail(request, project_id):
    ## Tutorials
    if request.user.is_anonymous:
        xuser_tutorial = False
    else:
        xuser = ExtendedUser.objects.get(user=request.user)
        xuser_tutorial = xuser.display_tutorial

    tutorial = True
    # Dismiss the tutorial
    if "dismiss_this" in request.POST:
        tutorial = False

    # Dismiss all tutorials
    if "dismiss_all" in request.POST:
        xuser.display_tutorial = False
        xuser.save()

    project = get_object_or_404(Project, id=project_id)
    samples = Sample.objects.filter(project_title_id=project_id)
    project_lipids = Project_Lipid.objects.filter(project_title_id=project_id)
    project_user_lipid_volumes = Project_User_Lipid_Volume.objects.filter(project_title_id=project_id)

    x = project.system_tempurature

    # Calculate or retrieve the volume and pair it with the lipid for display
        # Workaround for PostgreSQL type issue
    lipids_and_volumes = []
    for lipid in project_lipids:
        if lipid.project_lipid_name:
            calc_volume = round(eval(lipid.project_lipid_name.total_volume_equation) - lipid.project_lipid_name.hg_volume, 2)
            lipids_and_volumes.append([lipid, calc_volume])
        elif project_user_lipid_volumes:
            check = False
            for volume in project_user_lipid_volumes:
                if volume.project_user_lipid_name == lipid.project_user_lipid_name:
                    lipids_and_volumes.append([lipid, volume])
                    check = True
                    break
                
            if not check:
                lipids_and_volumes.append([lipid, 0])
        else:
            lipids_and_volumes.append([lipid, 0])

    return render(
        request,
        'viewer/project_detail.html', {
            'tutorial':tutorial,
            'xuser_tutorial':xuser_tutorial,
            'project':project,
            'lipids_and_volumes':lipids_and_volumes,
            'samples':samples,
        }
    )

# Edit an existing project
def project_edit(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if request.method == 'POST':
        form = Project_Form(request.POST, instance=project)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()
            return redirect('viewer:project_detail', project_id=project.id)
    else:
        form = Project_Form(instance=project)

    return render(request, 'viewer/form.html', {'project':project, 'form': form})

# Allow users to use advanced options (vary volume parameters mostly)
def project_advanced_options(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if request.method == 'POST':
        form = Advanced_Options(request.POST, instance=project)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()
            return redirect('viewer:project_detail', project_id=project.id)
    else:
        form = Advanced_Options(instance=project)

    return render(request, 'viewer/form.html', {'project':project, 'form': form})

# Delete project
def project_delete_warning(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    
    if request.method == 'POST':
        project.delete()
        return redirect('viewer:project_list')

    return render(request, 'viewer/project_delete_warning.html', {'project':project})

## Project Lipids
# Add lipids to a project
def project_lipid_new(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    owner = request.user

    if request.method == 'POST':
        form = Project_Lipid_Form(owner, request.POST)
        if form.is_valid():
            lipids = form.save(commit=False)
            lipids.project_title = project
            lipids.save()
            return redirect('viewer:project_detail', project_id=project.id)
    else:
        form = Project_Lipid_Form(owner)

    return render(request, 'viewer/form.html', {'project':project, 'form': form})

# Delete project lipid
def project_lipid_delete_warning(request, project_id, lipid_id):
    project = get_object_or_404(Project, id=project_id)
    lipid = get_object_or_404(Project_Lipid, id=lipid_id)
    
    if request.method == 'POST':
        lipid.delete()
        return redirect('viewer:project_detail', project_id=project.id)

    return render(request, 'viewer/delete_warning.html', {'project':project, 'project_lipid':lipid})

# Project custom lipid volume
def project_user_lipid_volume_new(request, project_id, lipid_id):
    project = get_object_or_404(Project, id=project_id)
    lipid = get_object_or_404(User_Lipid, id=lipid_id)

    if request.method == 'POST':

mysite/viewer/templates/viewer/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}

{% load staticfiles%}

{% block content %}

    {% if user.is_authenticated %}
        {% if tutorial and xuser_tutorial %}
            <div class="announcement">
                <h2>Tutorials</h2>
                <p>These tutorials are designed to help you understand how to use this tool. <strong>If you accidentally disable these tutorials and need to bring them back, you can find a link to do so at the bottom of every page.</strong></p>
                <p>This project is currently in <strong>alpha version 0.8</strong>, and is therefore not production ready. Some features are currently in development, and may not preform as expected. Thanks for your patience.</p>
                <p><strong>This site requires the use of cookies.</strong></p>
                <p>
                    <form id="inline" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="dismiss_this" style="margin-right: 15px;">Temporarily dismiss <strong>just this</strong> tutorial</button>
                    </form>
                    <form id="inline" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="dismiss_all">Permanently dismiss <strong>all</strong> tutorials</button>
                    </form>
                </p>
            </div>
        {% endif %}
    {% endif %}

    <div class="content-box">
        <h1>Vesicle Viewer - Lipid Bilayer SAS Data Visualization Tool</h1>

        <div class='right-image'><img src="{% static "viewer/images/lipidgraph.png" %}"
                alt="Example lipid composition probability graph" width="400px"></div>

        <h2>Upload your data</h2>
        <p>Upload and store expeirmental results.</p>

        <h2>Set your parameters</h2>
        <p>Set default values for parameters based on your needs and decide which ones fluxuate.</p>

        <h2>Visualize your data</h2>
        <p>Prepare and download graphs showcasing your results.</p>
    </div>
    <div class="content-box">
        <h2>Find out more</h2>
        <p><a href="{% url 'viewer:about' %}">Learn more about the Vesicle Viewer project and how to cite it in your work.</a></p>
        <p><a href="{% url 'viewer:help' %}">Find tutorials and more information on how the tool works.</a></p>
        <p><a href="{% url 'viewer:privacy' %}">We're commited to keeping your data secure and private - read our privacy policy here.</a></p>
    </div>

{% endblock content %}

mysite/viewer/templates/viewer/molecule_detail.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}

{% load staticfiles%}

{% block content %}

    <div class="content-box">
        <h1>{{ molecule.compound_name }}</h1>
    </div>
    <div class="content-box">
        <h2>Overall</h2>
        <div class="indent">
            <p><strong>Volume Equation:</strong> {{ molecule.total_volume_equation }}</p>
            <p><strong>Scattering Length:</strong> {{ molecule.scattering_length }}</p>
            <p><strong>Number of Electrons:</strong> {{ molecule.electrons }}</p>
        </div>
        <p></p>
    </div>

{% endblock content %}

mysite/viewer/templates/viewer/project_detail.html
{% extends 'base.html' %}
{% block title %}{{ project.project_title }}{% endblock title %}

{% load staticfiles %}
{% block content %}
    {% if user.is_authenticated %}

        {% if tutorial and xuser_tutorial %}
            <div class="announcement">
                <h3>Project Details</h3>
                <p>This page shows you all the details of a particular project.</p>
                <p>
                    <form id="inline" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="dismiss_this" style="margin-right: 15px;">Temporarily dismiss <strong>just this page's</strong> tutorials</button>
                    </form>
                    <form id="inline" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="dismiss_all">Permanently dismiss <strong>all</strong> tutorials</button>
                    </form>
                </p>
            </div>
        {% endif %}

    <div class="content-box">
        
        <h1>{{ project.project_title }}</h1><br />

        <h3  id="inline"><a href="{% url 'viewer:project_edit' project_id=project.id %}">Edit this project</a> or </h3>
        <h3  id="inline"> <a href="{% url 'viewer:project_delete_warning' project_id=project.id %}">Delete this project</a></h3>

    </div>

    {% if tutorial and xuser_tutorial %}
        <div class="announcement">
            <p>The <strong>model</strong> specifies which math is used to process your system, based on it's characteristics.</p>
            <p>Advanced options are available for users who require more flexibility in the model. <strong>Enabling these options may make your analysis more difficult.</strong></p>
        </div>
    {% endif %}

    <div class="content-box">

        <h2>Project Details</h2>

        <p>
            <h4 class="project-lipids indent" id="inline">Model: </h4> 
            {% if project.model_type == 'AS' %}
                Asymmetrical
            {% else %}
                Symmetrical
            {% endif %}
        </p>
        <p><h4 class="project-lipids indent" id="inline">Temp: </h4> {{ project.system_tempurature }} &degC</h4></p>
        <p class="indent"><a href="{% url 'viewer:project_advanced_options' project_id=project.id %}">Advanced options</a></p>

    </div>

    {% if tutorial and xuser_tutorial %}
        <div class="announcement">
            <p>Here you should specify the <strong>"common" or "nomial"</strong> versions of the lipids found in this project. Later on, you'll be able to specify specific versions of these lipids, including different dueterated versions, and creating other augmentations yourself.</p>
        </div>
    {% endif %}

    <div class="content-box">

        <h2>Lipids</h2>

        <p>The lipids present in this project.</p>

        {% if lipids_and_volumes %}
            <table class="project-lipids indent">
                <tr>
                    <td><h4>Name</h4></td>
                    <td><h4>Volume  [&#8491;<sup>3</sup>]</h4></td>
                    <td></td>
                    <td></td>
                </tr>
                {% for lipid in lipids_and_volumes %}
                    <tr>
                        {% if lipid.0.project_lipid_name %}
                            <td><a href="{% url 'viewer:lipid_detail' lipid_name=lipid.0.project_lipid_name.slug %}">{{ lipid.0.project_lipid_name }}</a></td>
                            <td>{{ lipid.1 }}</td>
                            <td></td>
                        {% else %}
                            <td><a href="{% url 'viewer:user_lipid_detail' owner=user.id lipid_name=lipid.0.project_user_lipid_name.slug %}">{{ lipid.0.project_user_lipid_name }}</a></td>
                            <td>
                                {% if lipid.1 != 0 and lipid.1.user_lipid_volume != 0 %}
                                {{ lipid.1.user_lipid_volume }}
                                <td><a href="{% url 'viewer:project_user_lipid_volume_edit' project_id=project.id volume_id=lipid.1.id %}">edit</a></td>
                                {% else %}
                                    <td><a href="{% url 'viewer:project_user_lipid_volume_new' project_id=project.id lipid_id=lipid.0.project_user_lipid_name.id %}">Add Volume</a></td>
                                {% endif %}
                            </td>
                        {% endif %}
                        <td><a href="{% url 'viewer:project_lipid_delete_warning' project_id=project.id lipid_id=lipid.0.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </table>

            <h3><a href="{% url 'viewer:project_lipid_new' project_id=project.id %}">Add another lipid</a></h3>

        {% else %}
            <h3><a href="{% url 'viewer:project_lipid_new' project_id=project.id %}">Add a lipid</a></h3>
        {% endif %}

    </div>

    {% if tutorial and xuser_tutorial %}
        <div class="announcement">
            <p><strong>Samples</strong> contain your datasets and you analysis of those datasets.</p>
            <p>This structure is used to help keep things organized. You can create as many samples as you need for a given project. <strong>Samples will all use the tempurature, model, and sublist of lipids specified on the project level.</strong></p>
        </div>
    {% endif %}

    <div class="content-box">

        <h2>Data Samples & Fitting</h2>

        <p>A list of samples, each of which contain datasets and fitting parameters.</p>

        {% if samples %}

            <table class="project-lipids indent">

                <tr>
                    <td><h4>Name</h4></td>
                    <td></td>
                    <td></td>
                </tr>
                {% for sample in samples %}
                <tr>
                    <td><a href="{% url 'viewer:sample_detail' project_id=project.id sample_id=sample.id %}">{{ sample.sample_title }}</a></td>
                    <td><a href="{% url 'viewer:sample_edit' project_id=project.id  sample_id=sample.id %}">Edit</a></td>
                    <td><a href="{% url 'viewer:sample_delete_warning' project_id=project.id sample_id=sample.id %}">Delete</a></td>
                </tr>
                {% endfor %}

            </table>

            <h3><a href="{% url 'viewer:sample_new' project_id=project.id %}">Add another sample</a></h3>

        {% else %}
            <h3><a href="{% url 'viewer:sample_new' project_id=project.id %}">Add a sample</a></h3>
        {% endif %}

    </div>

    {% else %}

    <div class="content-box">
        <h1>You're not logged in</h1>

        <p>To view this page, please <a href="{% url 'login' %}">login</a>.</p>
    </div>

    {% endif %}

{% endblock content %}

mysite/viewer/templates/viewer/project_list.html
{% extends 'base.html' %}
{% block title %}{{ user.username }}'s Projects{% endblock title %}

{% load staticfiles%}

{% block content %}

    {% if user.is_authenticated %}

        {% if tutorial and xuser_tutorial %}
            <div class="announcement">
                <h3>Projects and Models</h3>
                <p>Here your projects are listed, organized by "model". A <strong>project</strong> stores all the information about a particular project that you're working on, including subprojects called samples where your data is stored. The <strong>model</strong> of a given project specifies which math is used to process the data in that project.</p>
                <h3>Custom Lipids</h3>
                <p>You also have the option here to enter your own custom lipids to use in any of your projects. You'll need some specific information in order to do that.</p>
                <p>
                    <form id="inline" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="dismiss_this" style="margin-right: 15px;">Temporarily dismiss <strong>just this</strong> tutorial</button>
                    </form>
                    <form id="inline" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="dismiss_all">Permanently dismiss <strong>all</strong> tutorials</button>
                    </form>
                </p>
            </div>
        {% endif %}

        <div id="left" style="width:60%; margin-top: -15px;">

            {% if symmetrical_projects %}

                <div class="content-box">
                        <h1>Symmetrical Projects</h1>

                    {% for project in symmetrical_projects %}

                        <div class="project">
                            <h3><a href="{% url 'viewer:project_detail' project_id=project.id %}">{{ project.project_title }}</a></h3>
                        </div>

                    {% endfor %}
                    
                </div>

            {% endif %}
            {% if asymmetrical_projects %}

                <div class="content-box">
                        <h1>Asymmetrical Projects</h1>

                    {% for project in asymmetrical_projects %}

                        <div class="project">
                            <h3><a href="{% url 'viewer:project_detail' project_id=project.id %}">{{ project.project_title }}</a></h3>
                        </div>

                    {% endfor %}
                    
                </div>

            {% endif %}

            <div class="content-box">
                <h1>New Project</h1>
                <button
                    type="button"
                    onclick="window.location.href='{% url 'viewer:project_new' %}'" >
                    Click here to start a new project
                </button>
            </div>
        
        </div>
        <div id="right" style="width:39%; margin-top: -15px;">

            {% if user_lipids %}

                <div class="content-box">
                    <h1>Custom Lipids</h1>
                        
                    <table>
                        {% for lipid in user_lipids %}
                        <tr>
                            <td><h3><a href="{% url 'viewer:user_lipid_detail' owner=user.id lipid_name=lipid.slug %}">{{ lipid.user_lipid_name }}</a></h3></td>
                            <td><p><a href="{% url 'viewer:user_lipid_edit' owner=user.id lipid_name=lipid.slug %}">edit</a></p></td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>

            {% endif %}

            <div class="content-box">
                <h1>New Custom Lipid</h1>
                <button
                    type="button"
                    onclick="window.location.href='{% url 'viewer:user_lipid_new' owner=user.id %}'" >
                    Click here to start a new project
                </button>
            </div>
        
        </div>

    {% else %}

    <div class="content-box">
        <h1>You're not logged in</h1>

        <p>To view this page, please <a href="{% url 'login' %}">login</a>.</p>
    </div>
    
    {% endif %}

{% endblock content %}

mysite/viewer/templates/viewer/project_start.html
{% extends 'base.html' %}
{% block title %}Get Started{% endblock title %}

{% load staticfiles%}

{% block content %}
    {% if user.is_authenticated %}

    <div class="content-box">
        <h1>Welcome {{ user.username }}</h1>

        <p>Login was successful! You can either begin a fresh project or continue working.</p>

        <button
            type="button" 
            onclick="window.location.href='{% url 'viewer:project_new' %}'" >
            Start a new project
        </button>

        <button 
            type="button" 
            onclick="window.location.href='{% url 'viewer:project_list' %}'" >
            Continue an extisting project
        </button>
    </div>

    {% else %}

    <div class="content-box">
        <h1>You're not logged in</h1>

        <p>To view this page, please <a href="{% url 'login' %}">login</a>.</p>
    </div>

    {% endif %}
{% endblock content %}